// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlotAd_Globe.Data;

#nullable disable

namespace SlotAd_Globe.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505062920_ToolsAuditSessionAuditDate")]
    partial class ToolsAuditSessionAuditDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SlotAd_Globe.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastReportUploadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SlotAd_Globe.Data.ReportDashboardArchiveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CsvSourceKind")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvictedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("LegacyGenerateXlsxBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("PendingFilteredXlsxBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PendingKpiJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("StatusFilteredXlsxBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("StatusKpiJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UploadedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "UploadedUtc");

                    b.ToTable("ReportDashboardArchives", (string)null);
                });

            modelBuilder.Entity("SlotAd_Globe.Data.ReportUploadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CsvContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("CsvSourceKind")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UploadedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("CsvSourceKind", "UploadedUtc");

                    b.HasIndex("UserId", "UploadedUtc");

                    b.ToTable("ReportUploads", (string)null);
                });

            modelBuilder.Entity("SlotAd_Globe.Data.ToolAuditEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RawValue")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "TechnicianName");

                    b.HasIndex("SessionId", "ToolName", "Status");

                    b.ToTable("ToolAuditEntries", (string)null);
                });

            modelBuilder.Entity("SlotAd_Globe.Data.ToolAuditSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("AuditDate")
                        .HasColumnType("date");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("WeekStartDate");

                    b.HasIndex("UploadedByUserId", "UploadedUtc");

                    b.ToTable("ToolAuditSessions", (string)null);
                });

            modelBuilder.Entity("SlotAd_Globe.Data.ReportDashboardArchiveEntity", b =>
                {
                    b.HasOne("SlotAd_Globe.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlotAd_Globe.Data.ReportUploadEntity", b =>
                {
                    b.HasOne("SlotAd_Globe.Data.AppUser", "User")
                        .WithMany("ReportUploads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SlotAd_Globe.Data.ToolAuditEntryEntity", b =>
                {
                    b.HasOne("SlotAd_Globe.Data.ToolAuditSessionEntity", "Session")
                        .WithMany("Entries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SlotAd_Globe.Data.ToolAuditSessionEntity", b =>
                {
                    b.HasOne("SlotAd_Globe.Data.AppUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("SlotAd_Globe.Data.AppUser", b =>
                {
                    b.Navigation("ReportUploads");
                });

            modelBuilder.Entity("SlotAd_Globe.Data.ToolAuditSessionEntity", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
